"""add session_agent_kind to chats

Revision ID: 42812b49a880
Revises: 71f316f43abf
Create Date: 2026-04-01 14:09:14.038852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42812b49a880'
down_revision: Union[str, None] = '71f316f43abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('session_agent_kind', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'session_agent_kind')
    # ### end Alembic commands ###
