"""Drop checkpoint_id from messages

Revision ID: 5c682572fd0a
Revises: bf49a708566f
Create Date: 2026-03-05 06:51:12.946851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c682572fd0a'
down_revision: Union[str, None] = 'bf49a708566f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'checkpoint_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('checkpoint_id', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
