"""drop auto_compact_disabled and attribution_disabled columns

Revision ID: 671ba6b1f752
Revises: 74700ecc8f79
Create Date: 2026-04-15 04:23:21.700536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671ba6b1f752'
down_revision: Union[str, None] = '74700ecc8f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'attribution_disabled')
    op.drop_column('user_settings', 'auto_compact_disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('auto_compact_disabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user_settings', sa.Column('attribution_disabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
