"""drop custom_providers column

Revision ID: 71f316f43abf
Revises: a507e3781c77
Create Date: 2026-04-01 00:42:49.394904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f316f43abf'
down_revision: Union[str, None] = 'a507e3781c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'custom_providers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('custom_providers', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
