"""drop custom_mcps and installed_plugins columns

Revision ID: 74700ecc8f79
Revises: e9b8a677d86b
Create Date: 2026-04-06 01:19:43.525492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74700ecc8f79'
down_revision: Union[str, None] = 'e9b8a677d86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'timezone')
    op.drop_column('user_settings', 'installed_plugins')
    op.drop_column('user_settings', 'custom_mcps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('custom_mcps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_settings', sa.Column('installed_plugins', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_settings', sa.Column('timezone', sa.VARCHAR(length=64), server_default=sa.text("'UTC'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
