"""add worktree_cwd to chats

Revision ID: 852cfc68e9d3
Revises: 62500b9dae7b
Create Date: 2026-03-15 10:11:36.911256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852cfc68e9d3'
down_revision: Union[str, None] = '62500b9dae7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('worktree_cwd', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'worktree_cwd')
    # ### end Alembic commands ###
