"""Drop gmail oauth columns

Revision ID: 9cfb371853dc
Revises: 5c682572fd0a
Create Date: 2026-03-07 05:18:51.126458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cfb371853dc'
down_revision: Union[str, None] = '5c682572fd0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'gmail_oauth_tokens')
    op.drop_column('user_settings', 'gmail_email')
    op.drop_column('user_settings', 'gmail_oauth_client')
    op.drop_column('user_settings', 'gmail_connected_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('gmail_connected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user_settings', sa.Column('gmail_oauth_client', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('user_settings', sa.Column('gmail_email', sa.VARCHAR(length=320), autoincrement=False, nullable=True))
    op.add_column('user_settings', sa.Column('gmail_oauth_tokens', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
