"""add parent_chat_id to chats

Revision ID: a507e3781c77
Revises: 079863657461
Create Date: 2026-03-21 11:44:21.694754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types import GUID

# revision identifiers, used by Alembic.
revision: str = 'a507e3781c77'
down_revision: Union[str, None] = '079863657461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('parent_chat_id', GUID(), nullable=True))
    op.create_index('idx_chats_parent_chat_id', 'chats', ['parent_chat_id'], unique=False)
    op.create_foreign_key('fk_chats_parent_chat_id', 'chats', 'chats', ['parent_chat_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_chats_parent_chat_id', 'chats', type_='foreignkey')
    op.drop_index('idx_chats_parent_chat_id', table_name='chats')
    op.drop_column('chats', 'parent_chat_id')
    # ### end Alembic commands ###
